### PR TITLE
Add coveralls

### PR DESCRIPTION
**Pull request by dianpan**
Added Coveralls and the badge to Readme, so that we can:
1. see how much code coverage we have now
2. encourage others to write more tests and help increase our coverage %

### CODE REVIEW

**Comment by Roenok** [comment]
Thanks @dianpan! I'm seeing some merge conflicts with this one. Can you double-check you have the latest files from the master repo?

**Comment by kstack7** [comment]
Any update on this, @dianpan?

**Comment by dianpan** [comment]
@kstack7 sorry for the delay, I fixed the merge conflicts.

**Comment by kstack7** [comment]
Thanks for the conflict cleanup, @dianpan, and for including the push I skipped on staging (woops!)...let's see how this rolls on staging now :)

**Pull request merged**
