### PR TITLE
adding check for sold out classes; fixes #233

### LINKED ISSUE #233: Do not display closed/sold out classes on chapter page
**Description**
Closed & sold out classes currently appear in the available class list at top of Chapter Page template. 

**Ask**
Not sure if the Meetup API has the appropriate endpoint but it would be awesome if closed or sold out classes did not appear on available classes list on the chapter pages. For example, our page currently displays a Wordpress workshop that is already sold out (meanwhile we have 3 other classes open that don't yet show up on our top 3 on the chapter page). 

**To Do**
* [ ] Confirm if Meetup API supports an endpoint that informs whether a class is closed/sold out
* [ ] Modify chapter pg template to no longer display classes that are not available for registration

*Additional Info*
For example, see https://www.girldevelopit.com/chapters/cincinnati -- this class is currently sold out thus would prefer that it not be displayed http://www.meetup.com/Girl-Develop-It-Cincinnati/events/218895024/

### PR DESCRIPTION
**Pull request by minamarkham**

### CODE REVIEW

**Comment by DBNess** [comment]
:raised_hands: nice, @minamarkham!!!

**Comment by kstack7** [comment]
hey @minamarkham ...I'm looking at the logic and I think we need to swap the logic in the if statements:

typeof course.yes_rsvp_count !== "undefined " && course.yes_rsvp_count >= course.rsvp_limit

should be

typeof course.rsvp_limit !== "undefined " && course.yes_rsvp_count >= course.rsvp_limit

since the yes_rsvp_count is always available (basically a head count) while not every event has to have a posted limit (rsvp_limit). So then it reads "if there is a rsvp limit and the "yes" count is greater than it, then show SOLD OUT" kinda thing.

Make sense?

**Comment by kstack7** [comment]
SO glad you're taking a stab at this! Thank you thank you thank youuuu

**Comment by kstack7** [comment]
hah way to take FOREVER on that fix ;) nice! :+1:

**Comment by minamarkham** [comment]
@kstack7 :laughing: 

FYI I used Austin and Philly to test for full classes.

**Comment by kstack7** [comment]
Perfect. I think the logic is sound so we'll push it to tinker a bit more :) That's what staging is for anyways! Thanks again :)

**Comment by kstack7** [comment]
https://girl-develop-it-staging.herokuapp.com/chapters/philadelphia :)

**Comment by minamarkham** [comment]
https://girl-develop-it-staging.herokuapp.com/chapters/austin <-- without the map

**Comment by kstack7** [comment]
Perfecto! Looks solid to me...

**Pull request merged**
