### PR TITLE
Replace "him or her" in Code of Conduct

### PR DESCRIPTION
**Pull request by gnarf**
#391 - but targeted to the staging branch

P.S.  --- This was actually kind of a pain in the ass since your staging branch is behind production (you never fastforwared it to contain the merge commit from staging -> production) so I had to completely recreate the PR since I'm not on my normal computer with git, and I'm using github's built in editor.

Perhaps you should consider just landing the PR on staging yourself next time for your testing purposes, especially with a content only change in a view html file.

Thanks for the consideration!

### CODE REVIEW

**Comment by Roenok** [comment]
Thanks @gnarf! I'll bring up the suggestion at our next meeting. We are always looking for ways to make the process easier.

**Comment by gnarf** [comment]
You also might want to set the "main development branch" on github to be "staging" so all pull requests default to being against staging, and the view when you open up the repo gives you the staging branch.

This will ensure 99% of your contributors are sending PR's against staging, and basing their changes in the current staging branch

**Comment by Roenok** [comment]
Thanks for both the language updates and the process suggestions, @gnarf. We've changed the default branch to staging

**Comment by gnarf** [comment]
Awesome! I think this will help you and future contributors doing the right thing!

Thanks for taking this PR, and the great events and community.  GDI Boston Code and Coffee is one of my favorite meetups to go to, can't wait to be in town again :)

:heart_eyes:

**Pull request merged**
