### PR TITLE
closes #451 adds FAQ section to the about page

### LINKED ISSUE #451: Add link to FAQ on About page
Please add link to FAQ's on the About page - between "Our Board" and "Contact Us".  Suggested text: 

Have a question about GDI? Visit our [FAQ page](https://www.girldevelopit.com/faq)

### PR DESCRIPTION
**Pull request by jisoo-hisoo**

### CODE REVIEW

**Comment by kstack7** [comment]
Hey @jshin91! Thank you for your contribution :) I'm going to include a screenshot of your work so folks can see the changes you've made. Adding a screenshot to any PRs can help with the discussion to ensure we like the design changes going forward. Thanks again!
- Added FAQ section with link:
  screen shot 2016-04-28 at 4 28 05 pm

**Comment by kstack7** [comment]
Code checks out..just a matter of if we like the section there or in a different format 👍

**Comment by GretchenLynd** [comment]
Hi all -
Placement looks great! After seeing it, we're thinking it may need some additional text though. Can we replace the single line with: 

Want to learn more about our classes? Interested in contacting your local chapter? To learn more about GDI and to get answers to your questions, check out our [FAQ](https://www.girldevelopit.com/faq)!

**Comment by jisoo-hisoo** [comment]
Sure @GretchenLynd. Added the additional text!

screen shot 2016-04-29 at 12 57 37 pm

**Comment by corinnepw** [comment]
Looks great! Thanks @GretchenLynd @jshin91!

**Comment by GretchenLynd** [comment]
Perfect! Thanks so much for the quick turnaround! @jshin91

**Comment by kstack7** [comment]
Ruh roh @jshin91 ...feeling up to fixing this merge conflict? Likely due to the small changes on a recent PR...Let me know if you'd like me to instead 👍

**Comment by jisoo-hisoo** [comment]
Hey @kstack7. I'm not going to be able to get to it tonight so feel free to! Thanks!

**Comment by kstack7** [comment]
Ah so I need access to your repo in order to fix the conflicts...I've ported your code to a new branch and am merging it ( #456 ) in from my repo...I also added a line break to reduce the sentence length across the screen.

Original:
screen shot 2016-04-30 at 3 29 06 pm

Update with break: 
screen shot 2016-04-30 at 3 42 10 pm

Thanks again for the help! 🚀

**Pull request closed without merging**
