### PR TITLE
closes #449 Nonprofit info

### LINKED ISSUE #449: Add Nonprofit info to footer
Can you please add the following information to the footer of the site? 

Girl Develop It, 1522 Cole Street, Enumclaw, WA, 98022, USA 
_Girl Develop It is an exempt organization as described in Section 501(c)(3) of the Internal Revenue Code. Our EIN is 46-3103695._

### PR DESCRIPTION
**Pull request by jisoo-hisoo**

### CODE REVIEW

**Comment by kstack7** [comment]
@jshin91 you're on a roll! Can you add a screenshot of your work with your PR so we can see your changes? Thank you!

**Comment by jisoo-hisoo** [comment]
Sure @kstack7 

Here's a screenshot of the changes
screen shot 2016-04-28 at 5 00 26 pm

**Comment by kstack7** [comment]
Awesome! That's super helpful so thank you :)

**Comment by kstack7** [comment]
Code looks great, but asked if the italicized sentences are to be consistent here as in the issue: https://github.com/girldevelopit/gdi-website/issues/449

I'll merge this if not. 👍

**Comment by kstack7** [comment]
Yup! @corinnepw verified that the italicized sentences are necessary for this task...are you able to update the files @jshin91?

**Comment by jisoo-hisoo** [comment]
Sure, @kstack7. Updated! 
screen shot 2016-04-29 at 12 09 12 pm

**Comment by kstack7** [comment]
Awesome! 👍 thank you for the follow-up code :)

**Comment by corinnepw** [comment]
🙌  thank you so much @jshin91 & @kstack7!

**Pull request merged**
