### PR TITLE
Issue #345 - remove grayscale from sponsor icons

### PR DESCRIPTION
**Pull request by NewtCobell**
I removed the grayscale hover effect and added a tilt effect.  Simple enough to remove if you don't like it...

### CODE REVIEW

**Comment by NewtCobell** [comment]
Oh - the effect I added is demonstrated here (it's the tilt effect on the left).  I'm not 100% sure I'm in love with it, so I'm happy to check out other effects if you guys aren't wild about it: https://designshack.net/tutorialexamples/imagehovers/transforms.html

**Comment by Roenok** [comment]
@NewtCobell I like the tilt; it's nice and subtle. However, can we make the hover effect appear with the :focus state as well? I want our keyboard-only users to see it too.

**Comment by NewtCobell** [comment]
Thanks @Roenok! Sure, I don't see any reason why we can't do that on :focus as well.  I'll update the code.  :)

**Comment by kstack7** [comment]
Thanks for your contribution, @NewtCobell! Going to push this and let folks see it before a production push...

**Comment by kstack7** [comment]
So upon further inspection, we're thinking the tilt is a lil aggressive for our subtle design/look-and-feel...would you mind reverting back to the previous gray? We really enjoyed the chance to try something new or see how it looks, but we also want to maintain a more subtle level of interaction.

I'm happy to create a new issue if it helps to move from this closed PR.

Thanks @NewtCobell !!

**Comment by NewtCobell** [comment]
No worries - I'll take care of it today or tomorrow.

**Pull request merged**
