### PR TITLE
attempt on #320

### PR DESCRIPTION
**Pull request by johnmarinelli**
'vision' and 'values' should be stacked rather than side by side

### CODE REVIEW

**Comment by DBNess** [comment]
hey @johnmarinelli :clap: can you please include a screenshot for these visual changes when you get a chance? thank you!

**Comment by johnmarinelli** [comment]
yep, sure thing:
gdi

**Comment by amygori** [comment]
Wondering -- are these proposed changes for usability/accessibility or more of a design preference?  I am no usability expert, so I'm curious if there are concerns there.  

Also, not sure this is obvious: there are existing media queries to stack the text and justify to the left at smaller screen widths.

**Comment by kstack7** [comment]
Hey @amygori ...I suggested to @johnmarinelli that he share his screenshot on #320 so that we can all discuss the changes as a group. You can toss in your ideas there, too! :+1:

**Comment by amygori** [comment]
Thanks @kstack7 for the expert issue-wrangling and the heads up! I appreciate that -- figured there was probably context I was missing!!

**Comment by kstack7** [comment]
Hah yeah! We keep the discussions on the issues side. Thanks for chiming in! :+1:

**Pull request merged**
