### PR TITLE
Updated language on the donate page, adresses issue #197

### PR DESCRIPTION
**Pull request by alohaas**
@corinnepw @kstack7 let me know what you think of the following updates. 
One note is that '#GDIDay' in the 'Celebrate...' heading links to https://twitter.com/search?q=%23GDIDay&src=typd

If the design is satisfactory, I'll go back in and make the appropriate accomodations for responsive/cross-browser.

donate_language_updates

### CODE REVIEW

**Comment by kstack7** [comment]
Well done, @alohaas! I think it looks lovely :) One thing we were discussing was to put another donate button higher up on the page so that folks don't have to scroll all the way down. Do you have any suggestions for this? We were thinking that under the map/first paragraph would make most sense.

Are those GDIDay images the same size? The first block looks taller than the other two...wasn't sure if this was demonstrating a rollover feature or not. 

@Roenok, want to review the css portion and @corinnepw, double-check the content?

I'll apply dynamic code for the chapter counts once we've merged this in.

Go, team, go!

**Comment by alohaas** [comment]
Thanks!

@kstack7 good catch on the image sizes. That's an error. I can make sure they're all the same height. I was thinking that it might be nice to include an image rollover for each - "sweatshirt", "water bottle", "sticker". Should the images link anywhere?

I like the idea of putting the donate under the map/first paragraph. I can add the button in and see how it looks.

@Roenok one thing – on the 'About Page', `id="headline"` is used multiple times. I copied this pattern, but if you're okay with it, I'd rather switch it to `class="headline"` across the site. There shouldn't be more than one id with the name name on a page.

**Comment by alohaas** [comment]
@kstack7 updated screenshot with the new donate button and equal image heights:

donate_language_updates

**Comment by corinnepw** [comment]
@alohaas @kstack7 this looks AMAZING! Sorry for not being clear about what to do with what is already on the page, but everything between "Donate" and the Donate button on the page can be removed.

This part: _If you want to support women in technology and women transitioning into tech careers today, you can help us improve the technology industry's diversity problem now. We appreciate all contributions from individuals and companies of any amount, and we put them to good use to grow the amount of and impact on our students. All donations are 501c3 tax-deductible. By supporting Girl Develop It, you are supporting the ideal that it’s never too late to learn. Girl Develop It engages students from age 18-70, and we firmly believe that there should be avenues for women of all ages to benefit from the opportunities and rewards provided by learning web development._

It could even be replaced with the "Help us Grow" text/section?

**Comment by alohaas** [comment]
@corinnepw gotcha. I'll make the change.

**Comment by alohaas** [comment]
@corinnepw how is this change?
donate_language_updates

**Comment by Roenok** [comment]
@alohaas +1 on avoiding multiple IDs, as that can make some assistive tech break.

**Comment by alohaas** [comment]
@corinnepw @kstack7 let me know if you need me to make any more changes before tomorrow!

**Comment by kstack7** [comment]
This looks so lovely, @alohaas :) Solid job!! I'm excited :) If @corinnepw and others think it's good to go, I'll push it to staging, pull it down, and add some dynamic data to the content for some of those numbers. Then we should be good to push to production and go! Thanks for the big, big help :+1:

**Comment by corinnepw** [comment]
Yayayyay thank you all! Let's push 💪🏼

On Monday, January 11, 2016, Kristen notifications@github.com wrote:

> This looks so lovely, @alohaas https://github.com/alohaas :) Solid
> job!! I'm excited :) If @corinnepw https://github.com/corinnepw and
> others think it's good to go, I'll push it to staging, pull it down, and
> add some dynamic data to the content for some of those numbers. Then we
> should be good to push to production and go! Thanks for the big, big help [image:
> :+1:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/girldevelopit/gdi-new-site/pull/399#issuecomment-170729504
> .

## 

Corinne Warnshuis
Executive Director | Girl Develop It http://www.girldevelopit.com
corinne@girldevelopit.com | @corinnepw https://twitter.com/corinnepw |
831-331-1199

_Check out our upcoming classes and events on girldevelopit.com
http://girldevelopit.com._

**Comment by alohaas** [comment]
Woohoo! I'm glad you like it :grin: 
Excited to see it go live. 
Thanks everyone for the feedback along the way.

**Comment by DBNess** [comment]
have been lurking & making tweaks with @corinnepw and just wanted to add :raised_hands: thanks so much @alohaas @kstack7 @Roenok for this awesomeness :100:

**Comment by kstack7** [comment]
woo! k and we're deployed...pulling down for quick changes then back up we go...

https://girl-develop-it-staging.herokuapp.com/donate

**Comment by lzacharkow** [comment]
@alohaas @kstack7 Yaaaaaas! Beautiful work, ladies! :gem: :gem: :gem:

**Comment by alohaas** [comment]
:nail_care:

**Pull request merged**
