### PR TITLE
Closes #472: Update supporter logos

### LINKED ISSUE #472: Add & remove logos from Supporters page
**Add attached logo to Supporters page**

Sponsors:
_Add sponsor logo & link_
http://wtm.gdgthess.org/wp-content/uploads/2015/03/WT_logo_horizontal_pos.png
link to: http://www.womentechmakers.com

_Remove GE, Mandrill and Bloc_

### PR DESCRIPTION
**Pull request by elisekain**
Closes [#472](https://github.com/girldevelopit/gdi-website/issues/472).

Also slightly increased the height of the salesforce logo, so that the Women Techmakers logo wouldn't be orphaned in the bottom row at larger screen sizes.

### CODE REVIEW

**Comment by Roenok** [comment]
@elisekain Can you throw up a screenshot of what it looks like?

**Comment by elisekain** [comment]
@Roenok Yep! Giving you three since it looks different at different screen sizes.

### Small

supporters_small

### Medium

supporters_medium

### Large

supporters_large

**Comment by Roenok** [comment]
Oooo, fancy! Thanks for taking this one so quickly, @elisekain

**Comment by kstack7** [comment]
Yowza! ⚡ Nice job, @elisekain :) Thanks for the help!

**Pull request merged**
