### PR TITLE
Infographic on donate page

### PR DESCRIPTION
**Pull request by lzacharkow**
This adds an infographic to the donate page. On mobile, most elements are hidden so that the donate button isn't pushed super far down the page. Here's how you can expect it to look above 640px:

Donate page

Here's a breakdown of the changes:
- `donate.html.erb`: new infographic markup
- `donate.css.scss`: new donate page stylesheet
- `modules.css.scss`: adjustments to existing infographic styles
- `about.html.erb`: adjustment to existing infographic markup
- lots of new SVGs in `infographic/` image folder

fyi @corinnepw !

### CODE REVIEW

**Comment by kstack7** [comment]
Thanks lady! Pushing this now then adding more content later :) One suggestion, @lzacharkow, is considering another "donate" button higher up on the page...any thoughts on that?

**Comment by therufs** [comment]
Oh my word I just died of awesome 💗💗💗💗💗

**Comment by corinnepw** [comment]
💓 can't wait to see this live! If possible, please update the 54 to be 52 match the 52 chapters referenced earlier.

**Comment by kstack7** [comment]
Yup! Merged into staging for now and will fix the dynamic chapter count with the upcoming content changes :+1:

**Comment by corinnepw** [comment]
:clap: :clap:

**Comment by DBNess** [comment]
🙌

On Wed, Jan 6, 2016 at 9:02 AM, Corinne notifications@github.com wrote:

> [image: :clap:] [image: :clap:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/girldevelopit/gdi-new-site/pull/397#issuecomment-169330344
> .

## 

Vanessa Hurst
Co-Founder | Girl Develop It http://www.girldevelopit.com | @girldevelopit
http://twitter.com/girldevelopit

Girl Develop It http://girldevelopit.com/ teaches women to code in over
54 cities! Help us celebrate five outstanding years by supporting #GDIday
on January 12, 2016
https://www.thunderclap.it/projects/36239-help-more-women-learn-to-code.

Women coders break new ground, and stereotypes - TODAY show
http://www.today.com/video/today/53924117

**Comment by lzacharkow** [comment]
@kstack7 I think that's a great idea! A quick win would be to add a donate button above or below the paragraph beneath the map. If we could skim this to a sentence, that would be even better for quick understanding, and hopefully quick donating :)

I'll take care of that this weekend and make a tiny PR.

**Pull request merged**
